- name: Define sql path
  set_fact:
    sql_table: "{{ riprap_home }}/riprap/riprap_table.sql"

- name: Create sql file
  copy:
    dest: "{{ sql_table }}"
    content: |
      CREATE TABLE IF NOT EXISTS fixity_check_event (
          id INT AUTO_INCREMENT,
          event_uuid varchar(50) NOT NULL,
          resource_id varchar(255) NOT NULL,
          timestamp varchar(50) NOT NULL,
          digest_algorithm varchar(50) NOT NULL,
          digest_value varchar(255) NOT NULL,
          event_detail varchar(50) NOT NULL,
          event_outcome varchar(50) NOT NULL,
          event_type varchar(50) NOT NULL,
          event_outcome_detail_note varchar(50) NOT NULL,
          PRIMARY KEY (id)
      )  ENGINE=INNODB;

- name:  Create table in database
  mysql_db:
    name: "{{ drupal_db_name }}"
    state: import
    target: "{{ sql_table }}"

- name: Delete table file
  file:
    path: "{{ sql_table }}"
    state: absent
